website/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from . import db
from .utils import salt_generator


class User(db.Model, UserMixin):
    username = db.Column(db.String(64), nullable=False)
    email = db.Column(db.String(128), primary_key=True)
    salt = db.Column(db.String(10), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)

    def __init__(self, username, email, password) -> None:
        self.username = username
        self.email = email
        self.salt = salt_generator(email)
        self.password = generate_password_hash(f"{password}-{self.salt}", method='sha256')

    def __repr__(self):
        return f"<{type(self).__name__} {self.email}>"

    def get_id(self):
        return self.email

    def has_valid(self, password):
        return check_password_hash(self.password, f"{password}-{self.salt}")


class Word(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    word = db.Column(db.String(50), nullable=False)
    pos = db.Column(db.String(16), nullable=False)
    user_id = db.Column(db.String(128), db.ForeignKey('user.email'), nullable=False)

    user = db.relationship('User', backref='words', lazy=True)

    def __repr__(self):
        return f"<{type(self).__name__} {self.word}, {self.pos}>"


class Meaning(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    meaning = db.Column(db.String(150), nullable=False)
    source = db.Column(db.String(50), nullable=False)
    user_id = db.Column(db.String(128), db.ForeignKey('user.email'), nullable=False)
    word_id = db.Column(db.Integer, db.ForeignKey('word.id'), nullable=False)

    user = db.relationship('User', backref='meanings', lazy=True)
    word = db.relationship("Word", backref="meanings", lazy=True)

    def __repr__(self):
        return f"<{type(self).__name__} {self.id}, {self.source}>"


class Example(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    example = db.Column(db.String(256), nullable=False)
    user_id = db.Column(db.String(128), db.ForeignKey('user.email'), nullable=False)
    word_id = db.Column(db.Integer, db.ForeignKey('word.id'), nullable=False)

    user = db.relationship('User', backref='examples', lazy=True)
    word = db.relationship('Word', backref='examples', lazy=True)

    def __repr__(self):
        return f"<{type(self).__name__} {self.id}, {self.user_id}>"

website/forms.py
from flask import Blueprint, request, redirect, flash
from flask_login import login_required, current_user

from website.utils import titlecase
from .models import Word, Meaning, Example
from . import db

forms = Blueprint('forms', __name__)


@forms.route('/add-word', methods=['POST'])
@login_required
def add_word():
    data = {
        'word': request.form['word'],
        'pos': request.form['pos'],
        'user': current_user,
    }
    word = Word.query.filter_by(word=data['word'], pos=data['pos']).first()
    if not word:
        word = Word(**data)
        db.session.add(word)
        db.session.commit()
        flash('Word added successfully!', category='success')
    else:
        flash('Word already exists!', category='warning')
    return redirect(request.referrer)


@forms.route('/add-meaning', methods=['POST'])
@login_required
def add_meaning():
    data = {
        'meaning': request.form['meaning'],
        'source': titlecase(request.form['source']),
        'word_id': request.form['word_id'],
        'user': current_user,
    }
    meaning = Meaning.query.filter_by(meaning=data['meaning'], source=data['source'], word_id=data['word_id']).first()
    if not meaning:
        meaning = Meaning(**data)
        db.session.add(meaning)
        db.session.commit()
        flash('Meaning added successfully!', category='success', )
    else:
        flash('Meaning already exists!', category='warning')
    return redirect(request.referrer)


@forms.route('/add-example', methods=['POST'])
@login_required
def add_example():
    data = {
        'example': request.form['example'],
        'word_id': request.form['word_id'],
        'user': current_user,
    }
    example = Example.query.filter_by(example=data['example'], word_id=data['word_id']).first()
    if not example:
        example = Example(**data)
        db.session.add(example)
        db.session.commit()
        flash('Example added successfully!', category='success', )
    else:
        flash('Example already exists!', category='warning')
    return redirect(request.referrer)

website/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from colorama import init, Fore
init(autoreset=True)

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = os.environ.get('my-app-key')
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    DB_NAME = "vocabs"
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///static/{DB_NAME}.db"
    db.init_app(app)

    from .views import views
    app.register_blueprint(views, url_prefix="/")
    from .auth import auth
    app.register_blueprint(auth, url_prefix="/")
    from .forms import forms
    app.register_blueprint(forms, url_prefix="/form")

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .models import User
    create_sqlite_db(app, DB_NAME)

    @login_manager.user_loader
    def load_user(email):
        return User.query.get(email)
    return app


def create_sqlite_db(app, db_name):
    if not os.path.exists(f"website/static/{db_name}.db"):
        print(f"{Fore.YELLOW}Creating database {db_name}...")
        db.create_all(app=app)
        print(f"{Fore.GREEN}Database {db_name} created!")

website/auth.py
from flask import Blueprint, request, redirect, flash
from flask_login import login_user, logout_user, login_required

from .models import User
from . import db

auth = Blueprint('auth', __name__)


@auth.route('/register', methods=['POST'])
def register():
    data = {
        "username": request.form.get('username'),
        "email": request.form.get('email'),
    }
    user: User = User.query.filter_by(email=data['email']).first()
    if not user:
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        if password1 == password2:
            data["password"] = password1
            user = User(**data)
            db.session.add(user)
            db.session.commit()
            flash('User registered successfully!', category='success')
            login_user(user, remember=True)
        else:
            flash('Passwords do not match!', category='error')
    else:
        flash('Email already exists!', category='warning')
    return redirect(request.referrer)


@auth.route('/login', methods=['POST'])
def login():
    data = {
        "email": request.form.get('email'),
    }
    user: User = User.query.filter_by(email=data['email']).first()
    if user:
        password = request.form.get('password')
        if user.has_valid(password):
            login_user(user, remember=True)
            flash('User logged in successfully!', category='success')
        else:
            flash('Incorrect password!', category='error')
    else:
        flash('Email is not registered!', category='warning')
    return redirect(request.referrer)


@auth.route('/logout', methods=['POST'])
@login_required
def logout():
    logout_user()
    flash('Logged out successfully!', category='success')
    return redirect(request.referrer)

website/views.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from .models import Word

views = Blueprint('views', __name__)


@views.route('/', methods=['GET'])
def home():
    data = {
        "words": Word.query.order_by(Word.word).all(),
    }
    return render_template('index.html', user=current_user, **data)


@views.route('/about', methods=['GET'])
def about():
    data = {}
    return '<h1>About</h1><hr><p>coming soon...</p>'


@views.route('/profile', methods=['GET'])
@login_required
def profile():
    data = {}
    return '<h1>Profile</h1><hr><p>coming soon...</p>'

website/templates/alerts.html
{% with messages = get_flashed_messages(with_categories=True) %}
{% if messages %}
<div class="alert-container">
    <div class="text-center">
        {% for category, message in messages %}
        {% if category == 'error' %}
        <div class="alert alert-danger">
            {% elif category == 'warning' %}
            <div class="alert alert-warning">
                {% elif category == 'success' %}
                <div class="alert alert-success">
                    {% endif %}
                    {{ message }}
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
        {% endwith %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="{{ url_for('static', filename='./images/favicon.png') }}" type="image/png">

  <!-- stylesheet/css -->
  <link rel="stylesheet" href="{{ url_for('static', filename='./assets/css/myStyle.css') }}">
  <!-- MDB -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.11.0/mdb.min.css" />

  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Serif+Bengali&display=swap">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />

  <title>{% block title %} {% endblock %} | Vocabs</title>
</head>

<body>
  <!-- Header -->
  {% include "header.html" %}
  <!-- Alerts -->
  <section class="mt-5 pt-2">
    {% include "alerts.html" %}
    <!-- Body -->
    {% block body %} {% endblock %}
  </section>
  <!-- Footer -->
  {% include "footer.html" %}

  <!-- scripts/js -->
  <script src="{{ url_for('static', filename='./assets/js/myScript.js') }}"></script>
  <!-- MDB -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.11.0/mdb.min.js"></script>

</body>

</html>

website/templates/footer.html
<!-- Footer -->
<footer class="bg-grey-25 text-center ">
    <!-- Grid container -->
    <div class="container p-4">

        <!-- Section: Social media -->
        <section class="mb-4">
            <!-- Email -->
            <a class="btn btn-primary btn-floating m-1" style="background-color: #dd4b39"
                href="mailto:alimus.sifar@g.bracu.ac.bd" role="button"><i class="fas fa-envelope"></i></a>

            <!-- Facebook -->
            <a class="btn btn-primary btn-floating m-1" style="background-color: #3b5998"
                href="https://facebook.com/AlimusSifar" role="button"><i class="fab fa-facebook-f"></i></a>

            <!-- Twitter -->
            <!-- <a class="btn btn-primary btn-floating m-1" style="background-color: #55acee" href="#!" role="button"><i
                    class="fab fa-twitter"></i></a> -->

            <!-- Google -->
            <!-- <a class="btn btn-primary btn-floating m-1" style="background-color: #dd4b39" href="#!" role="button"><i
                    class="fab fa-google"></i></a> -->

            <!-- Instagram -->
            <!-- <a class="btn btn-primary btn-floating m-1" style="background-color: #ac2bac" href="#!" role="button"><i
                    class="fab fa-instagram"></i></a> -->

            <!-- Linkedin -->
            <a class="btn btn-primary btn-floating m-1" style="background-color: #0082ca"
                href="https://linkedin.com/in/AlimusSifar" role="button"><i class="fab fa-linkedin-in"></i></a>

            <!-- Github -->
            <a class="btn btn-primary btn-floating m-1" style="background-color: #333333"
                href="https://github.com/AlimusSifar" role="button"><i class="fab fa-github"></i></a>
        </section>
        <!-- Section: Social media -->

        <!-- Section: Text -->
        <section class="text-grey-75 mb-4">
            <h4>About</h4>
            <p>This website is under development. Please feel free to roam around, send feedback and report any bugs if
                you notice.</p>
        </section>
        <!-- Section: Text -->

    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3 nav-link disabled" style="background-color: rgba(0, 0, 0, 0.2)">
        <div class="text-grey-50">Copyright © 2022:
            <a class="text-grey-50" href="https://mdbootstrap.com/">All rights reserved</a>
        </div>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

website/templates/form-example.html
<div class="example-form">
  <form method="post">
    <div class="row align-items-center">
      <div class="col">
        <div class="form-outline">
          <input class="form-control" type="text" name="example" id="example-example" maxlength="256" required>
          <label class="form-label" for="example-example">Example</label>
        </div>
      </div>
      <input type="number" name="word_id" id="example-word_id" value="{{ word.id }}" hidden>
      <div class="col">
        <button class="btn btn-sm btn-dark" type="submit" formaction="{{ url_for('forms.add_example') }}">Add</button>
      </div>
    </div>
  </form>
</div>

website/templates/form-login.html
<div class="login-form">
  <form method="post">
    <div class="modal-body d-flex flex-column align-items-center">
      <h1 class="modal-title mb-4" id="modalLogin">Login</h1>
      <div class="form-outline w-80 mb-4">
        <input class="form-control form-control-lg" type="email" name="email" id="login-email" maxlength="128"
          placeholder="username@domain.com" required>
        <label class="form-label" for="login-email">Email</label>
      </div>
      <div class="form-outline w-80 mb-4">
        <input class="form-control form-control-lg" type="password" name="password" id="login-password" maxlength="128"
          required>
        <label class="form-label" for="login-password">Password</label>
      </div>
      <button type="submit" class="btn btn-primary mb-4" formaction="{{ url_for('auth.login') }}">Login</button>
      <div class="mb-4">
        <p>Not a member? <a type="button" href="" data-mdb-toggle="modal" data-mdb-target="#modalRegister">Register</a>
        </p>
      </div>
    </div>
  </form>
</div>

website/templates/form-meaning.html
<div class="meaning-form">
  <form method="post">
    <div class="row align-items-center">
      <div class="col">
        <div class="form-outline">
          <input class="form-control" type="text" name="meaning" id="meaning-meaning" maxlength="150" required>
          <label class="form-label" for="example-example">Meaning</label>
        </div>
      </div>
      <div class="col">
        <div class="form-outline">
          <input class="form-control" type="text" name="source" id="meaning-source" placeholder="Source" maxlength="50"
            required>
          <label class="form-label" for="example-example">Source</label>
        </div>
      </div>
      <input type="number" name="word_id" id="meaning-word_id" value="{{ word.id }}" hidden>
      <div class="col">
        <button class="btn btn-sm btn-dark" type="submit" formaction="{{ url_for('forms.add_meaning') }}">Add</button>
      </div>
    </div>
  </form>
</div>

website/templates/form-register.html
<div class="register-form">
  <form method="post">
    <div class="modal-body d-flex flex-column align-items-center">
      <h1 class="modal-title mb-4" id="modalRegister">Register</h1>
      <div class="form-outline w-80 mb-4">
        <input class="form-control form-control-lg" type="username" name="username" id="register-username"
          maxlength="128" required>
        <label class="form-label" for="register-username">Username</label>
      </div>
      <div class="form-outline w-80 mb-4">
        <input class="form-control form-control-lg" type="email" name="email" id="register-email"
          placeholder="username@domain.com" maxlength="128" required>
        <label class="form-label" for="register-email">Email</label>
      </div>
      <div class="form-outline w-80 mb-4">
        <input class="form-control form-control-lg" type="password" name="password1" id="register-password1"
          maxlength="128" required>
        <label class="form-label" for="register-password1">Password</label>
      </div>
      <div class="form-outline w-80 mb-4">
        <input class="form-control form-control-lg" type="password" name="password2" id="register-password2"
          maxlength="128" required>
        <label class="form-label" for="register-password2">Password confirmation</label>
      </div>
      <button type="submit" class="btn btn-primary mb-4" formaction="{{ url_for('auth.register') }}">Register</button>
      <div class="mb-4">
        <p>Already a member? <a type="button" href="" data-mdb-toggle="modal" data-mdb-target="#modalLogin">Login</a>
        </p>
      </div>
    </div>
  </form>
</div>

website/templates/form-word.html
<div class="word-form">
  <form method="post">
    <div class="modal-body d-flex flex-column align-items-center">
      <h1 class="modal-title mb-4" id="modalAddWordLabel">New Word</h1>
      <div class="form-outline w-80 mb-4">
        <input class="form-control form-control-lg" type="text" name="word" id="word-word" maxlength="50" required>
        <label class="form-label" for="word-word">Word</label>
      </div>
      <select class="select form-control form-control-lg w-80 mb-4" name="pos" id="word-pos" required>
        <option value="" selected disabled>Parts of Speech</option>
        <option value="noun">Noun</option>
        <option value="pronoun">Pronoun</option>
        <option value="adjective">Adjective</option>
        <option value="verb">Verb</option>
        <option value="adverb">Adverb</option>
        <option value="preposition">Preposition</option>
        <option value="conjunction">Conjunction</option>
        <option value="interjection">Interjection</option>
        <option value="determiner">Determiner</option>
      </select>
      <button type="submit" class="btn btn-primary mb-4" formaction="{{ url_for('forms.add_word') }}">Add</button>
    </div>
  </form>
</div>

website/templates/header.html
<!-- Navbar -->
{% include "navbar.html" %}

website/templates/index.html
{% extends "base.html" %} {% block title %} Home {% endblock %}
{% block body %}

<div class="container">

  <div class="d-flex justify-content-center">
    <!-- <h1 class="bangla">বোকাবুলারি</h1> -->
  </div>

  <!-- Show word list -->
  <div class="word-list w-100">
    {% include "wordlist.html" %}
  </div>

  {% if not user.is_anonymous %}
  <!-- Button trigger modal -->
  <div class="fixed-13-87">
    <a type="button" data-mdb-toggle="modal" data-mdb-target="#modalAddWord" title="Add word">
      <img src="{{ url_for('static', filename='./images/512px-plus.png') }}" alt="Logo" height="30" />
    </a>
  </div>

  {% endif %}
</div>

{% include "modal-word.html" %}

{% endblock %}

website/templates/modal-login.html
<!-- Modal Login -->
<div class="modal fade" id="modalLogin" tabindex="-1" aria-labelledby="modalLoginLabel" aria-hidden="true"
  data-mdb-backdrop="true" data-mdb-keyboard="true">
  <div class="modal-dialog modal-dialog-centered justify-content-center">
    <div class="modal-content w-80">
      {% include 'form-login.html' %}
    </div>
  </div>
</div>

website/templates/modal-register.html
<!-- Modal Register -->
<div class="modal fade" id="modalRegister" tabindex="-1" aria-labelledby="modalRegisterLabel" aria-hidden="true"
    data-mdb-backdrop="true" data-mdb-keyboard="true">
    <div class="modal-dialog modal-dialog-centered justify-content-center">
        <div class="modal-content w-80">
            {% include "form-register.html" %}
        </div>
    </div>
</div>

website/templates/modal-word.html
<!-- Modal -->
<div class="modal top fade" id="modalAddWord" tabindex="-1" aria-labelledby="modalAddWordLebel" aria-hidden="true"
  data-mdb-backdrop="true" data-mdb-keyboard="true">
  <div class="modal-dialog modal-dialog-centered justify-content-center">
    <div class="modal-content w-80">
      {% include 'form-word.html' %}
    </div>
  </div>
</div>

website/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-grey-25 fixed-top">
  <!-- Container wrapper -->
  <div class="container justify-content-between">
    <!-- Left elements -->
    <!-- Navbar brand -->
    <div class="d-flex">
      <a href="{{ url_for('views.home') }}" class="navbar-brand mt-2 mt-lg-0 align-items-baseline fw-bold">
        <img src="{{ url_for('static', filename='./images/logo-brand.png') }}" alt="Logo" height="30" />O C A B
        S
      </a>
    </div>
    <!-- Left elements -->

    <!-- Center elements -->
    <div class="navbar-nav flex-row d-none d-md-flex">
      <!-- Toggle button -->
      <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbar-contents"
        aria-controls="navbar-contents" aria-expanded="false" aria-label="Toggle navbar">
        <i class="fas fa-bars fa-xl"></i>
      </button>

      <!-- Search box -->
      <ul class="navbar-nav flex-row d-none d-md-flex">
        <form class="input-group w-auto">
          <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
            aria-describedby="search-addon" disabled />
          <span class="input-group-text border-0" id="search-addon">
            <button type="submit" class="btn btn-sm text-white" formaction="" disabled>
              <i class="fas fa-search"></i>
            </button>
          </span>
        </form>
      </ul>

      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbar-contents">
        <!-- Left links -->
        <!-- <div class="nav-link text-light">Link 1</div>
            <div class="nav-link text-light">Link 2</div>
            <div class="nav-link text-light">Link 3</div> -->
      </div>
      <!-- Collapsible wrapper -->
    </div>
    <!-- Center elements -->

    <!-- Right elements -->
    <ul class="navbar-nav flex-row">
      <li class="nav-item dropdown me-3 me-lg-1 d-flex">
        {% if not user.is_anonymous %}
        <a href="{{ url_for('views.profile') }}">
          <strong class="d-none d-sm-block text-light">{{ user.username }}</strong>
        </a>
        {% endif %}
        <a class="nav-link dropdown-toggle hidden-arrow d-sm-flex align-items-sm-center" id="navbarDropdownMenuLink"
          role="button" data-mdb-toggle="dropdown" aria-expanded="false">
          <i class="fas fa-user-circle fa-2xl text-light"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
          <!-- Button trigger modal -->
          {% if user.is_anonymous %}
          <li>
            <a type="button" class="dropdown-item" data-mdb-toggle="modal" data-mdb-target="#modalLogin">Login</a>
          </li>
          <li>
            <a type="button" class="dropdown-item" data-mdb-toggle="modal" data-mdb-target="#modalRegister">Register</a>
          </li>
          {% else %}
          <li>
            <a type="button" class="dropdown-item" href="{{ url_for('views.profile') }}">Profile</a>
          </li>
          <li>
            <form method="post">
              <button type="submit" class="dropdown-item" formaction="{{ url_for('auth.logout') }}">Logout</button>
            </form>
          </li>
          {% endif %}
        </ul>
      </li>
    </ul>
    <!-- Right elements -->
  </div>
</nav>

{% include "modal-login.html" %}
{% include "modal-register.html" %}